### ISSUE TITLE
Scanning any services

### ISSUE THREAD

**Issue by Raj-abm** [capacitor-community/bluetooth-le#132]
Hello sir, 
I came here for your help,
For scanning BLE devices how can I scan for devices independent of the service it is providing.
That is when I scan, I want the list of devices currently advertising, independent of the service it is providing,

`await BleClient.requestLEScan(
        {
          services: [HEART_RATE_SERVICE],
        },
        result => {
          console.log('received new scan result', result);
          setDevicesFound([...devicesFound,result]);
        },
      );`
this scans only devices advertising only heart_rate_service.
is there another version of `requestLEScan()`

**Comment by pwespi** [comment]
The `services` array is optional. You can use
```ts
await BleClient.requestLEScan({}, (result) => {
  console.log("received new scan result", result);
  setDevicesFound([...devicesFound, result]);
});
```
