### ISSUE TITLE
Connection attempt times out when trying to connect to a dual-mode Bluetooth chip

### ISSUE THREAD

**Issue by tozuro-it** [capacitor-community/bluetooth-le#138]
Hi,

Thank you very much for creating and sharing this plugin. Great work!

**Is your feature request related to a problem? Please describe.**
I've used the plugin in a simple Android test app and found a possible issue when connecting to some Bluetooth devices. Connecting to a device that includes a Bluetooth chip that only supports BLE works as expected. However, when attempting to connect to a device that contains a dual mode Bluetooth chip fails - connection attempt times out.

**Describe the solution you'd like**
Would it be possible to amend the Device.kt file of Android native code, line 165 to explicitly set the transport flag to BluetoothDevice.BluetoothDevice.TRANSPORT_LE?
Current version uses : `device.connectGatt(context, false, gattCallback)`

My request would change that to:
Current version uses : `device.connectGatt(context, false, gattCallback, BluetoothDevice.TRANSPORT_LE)`

This would require incrementing the minimum Android SDK to 23. Hopefully that wouldn't be too much of a problem as the plugin uses root project Gradle configuration anyway.
Alternatively one could also use conditional logic to support Android SDK < 23 using the existing version and >= 23 with the potential change to connectGatt() signature.

I would be happy to submit a PR with the abovementioned code change.

**Describe alternatives you've considered**
I tried the following to attempt to connect to my test Bluetooth device (all attempts failed):
1. Increasing connection timeout.
1. Sending connection request multiple times.
1. Creating a bond with the test device before trying to connect.

**Additional context**
My request only applies to Android. I don't have access to Apple development environment so I don't know if this applies to iOS too.

**Plugin version**
@capacitor-community/bluetooth-le: 1.1.1

Thank you in advance for your support!

**Comment by pwespi** [comment]
Thanks for reporting this and for suggesting a fix.

I went with the option to check for SDK version, as I prefer to keep the minimum Android SDK in sync with capacitor core.

PS: As I was doing some tests, I just implemented this myself. But feel free to submit PRs in the future if you like.

**Comment by tozuro-it** [comment]
Fantastic! Thank you very much for replying and implementing this. My test app is able to connect successfully to my test dual-mode Bluetooth device. Thanks again.
