### ISSUE TITLE
Error: Characteristic not found.

### ISSUE THREAD

**Issue by ferdiaddawy** [capacitor-community/bluetooth-le#147]
I always have the problem Error: Characteristic not found.

can anyone help with this problem?

 const bluetooth = async () => {
      const HEART_RATE_SERVICE = "0000180d-0000-1000-8000-00805f9b34fb";
      const HEART_RATE_MEASUREMENT_CHARACTERISTIC =
        "00002a37-0000-1000-8000-00805f9b34fb";
      const BODY_SENSOR_LOCATION_CHARACTERISTIC =
        "00002a38-0000-1000-8000-00805f9b34fb";
      const BATTERY_SERVICE = numberToUUID(0x180f);
      const BATTERY_CHARACTERISTIC = numberToUUID(0x2a19);
      const POLAR_PMD_SERVICE = "fb005c80-02e7-f387-1cad-8acd2d8df0c8";
      const POLAR_PMD_CONTROL_POINT = "fb005c81-02e7-f387-1cad-8acd2d8df0c8";
      await BleClient.initialize();
      const device = await BleClient.requestDevice({
        // services: [HEART_RATE_SERVICE],
        // optionalServices: [BATTERY_SERVICE, POLAR_PMD_SERVICE],
      });
      await BleClient.connect(device.deviceId);
      await BleClient.write(
        device.deviceId,
        POLAR_PMD_SERVICE,
        POLAR_PMD_CONTROL_POINT,
        numbersToDataView([1, 0])
      );
    };

    bluetooth();

**Comment by pwespi** [comment]
What device are you using? Are you sure that it has a characteristic with UUID `fb005c81-02e7-f387-1cad-8acd2d8df0c8`? If not, you will get the error `Characteristic not found`.
