### ISSUE TITLE
Differing requestLEScan results to OS BT settings

### ISSUE THREAD

**Issue by alexcroox** [capacitor-community/bluetooth-le#176]
**Describe the bug**
I'm trying to connect to a device for the first time, I'm using the following:

```
await BleClient.initialize()

await BleClient.requestLEScan({}, result => { console.log('received new scan result', result) })
```

and I get the following list:

![IMG_3731](https://user-images.githubusercontent.com/1065835/131181076-7c426d36-a9b4-48a1-9d7f-544ec1605aea.PNG)

However it doesn't contain the device I'm looking for, which immediately shows up in the iOS settings bluetooth section:

![IMG_3727](https://user-images.githubusercontent.com/1065835/131181133-925ae319-6c11-4e07-91da-651cdea1f398.jpg)

Would there be any reason for this? I'm pretty new to the BT world. It also shows up fine in my macbook bluetooth settings:

![image](https://user-images.githubusercontent.com/1065835/131182274-bae5c715-8bca-45fa-bac4-7eb8746fd20a.png)

**Comment by pwespi** [comment]
Yes, `Bluetooth Core Spec: 3.0` means your device is Bluetooth classic. This plugin is only for Bluetooth Low Energy.
