### ISSUE TITLE
Check if device is connected

### ISSUE THREAD

**Issue by kozakhs** [capacitor-community/bluetooth-le#183]
Hello,

please, is it possible to implement function to check whether bluetooth device is connected?
For example:
`isConnected(deviceId: string) =>  Promise <boolean> `

Thank you very much!

**Comment by mutasimissa** [comment]
I think you can use the method getconnectedDevices like this:

 const isConnected = await BleClient.getConnectedDevices([SOME_UUID_TO_FILTER_OR_GET_ALL])

**Comment by kozakhs** [comment]
> I think you can use the method getconnectedDevices like this:
> 
> const isConnected = await BleClient.getConnectedDevices([SOME_UUID_TO_FILTER_OR_GET_ALL])

Thats exactly what I need. Thank you very much! I did not realise I can do it this way :)

**Comment by mutasimissa** [comment]
You are welcome, Can you please close the issue?
