### ISSUE TITLE
Allow setting custom timeout

### ISSUE THREAD

**Issue by jastax** [capacitor-community/bluetooth-le#201]
Thanks for this package, I really like it. 

Feature Request:
I'm often running into timeouts when trying to connect with BLE devices. I'd like to be able to set a custom timeout by passing options.

**Comment by pwespi** [comment]
Thank you for using this plugin. This is a good suggestion. I will take it on the roadmap for the next version.

**Comment by pwespi** [comment]
Configuration of the connect timeout has been added with #242. This will be in the next release.
