### ISSUE TITLE
How to write a message instead of array of numbers?

### ISSUE THREAD

**Issue by Raj-abm** [capacitor-community/bluetooth-le#203]
Hello sir thanks for the plugin,

I am not reporting a bug, I want to know the usage of write function.

In usage section it is defined how to write an array of numbers.
I wanted to know, how can I write a message to characteristic using write function?
and how do I convert my string to DataView type?

Please let me know?

**Comment by pwespi** [comment]
There is a helper function `textToDataView` that you can use (it uses [charCodeAt](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/charCodeAt) under the hood).

```typescript
import { BleClient, textToDataView } from '@capacitor-community/bluetooth-le';

const dataView = textToDataView('hello');
await BleClient.write(device.deviceId, SERVICE, CHARACTERISTIC, dataView);
```

PS: To convert a DataView to a string, there is also `dataViewToText`.
