### ISSUE TITLE
Best practice to hand over connection between Vue components 

### ISSUE THREAD

**Issue by hecko** [capacitor-community/bluetooth-le#222]
I am seeking a little advice on how to hand over the BTLE connection between multiple Vue components. 
Lets say I connect to the BLE device in one component, then want to move to a different component where I manipulate data from the BLE device, but I still need to be connected to the device persistently and receive the subscribed-to characteristics.

I obviously do not want to be reconnecting to the device - just make the connection and subscription persistent over components (using Vue3 + Vue Router)

Any suggestion here? Just a quick pointers are perfectly fine, Ill dig-out the rest. Thanks!

**Comment by pwespi** [comment]
You should only store things like the deviceId and the values returned from BleClient, not the BleClient itself.

I'm closing this, as it's not directly related to the plugin. If there is any issue with the plugin functionality, please open a new issue with steps on how to reproduce. Thank you!
