### ISSUE TITLE
iOS - getConnectedDevices issue

### ISSUE THREAD

**Issue by kozakhs** [capacitor-community/bluetooth-le#224]
**Describe the bug**
I connect to a bt device using iPhone and then I start notifications on specific characteristic. At the same time I periodically check if device is connected (e.g. every 5 second) on background (using getConnectedDevices function), the callback "on received packet" stops calling after couple of packets. Then it seems no packets are received, but I've checked it, and the packets are being sent from the bt device. This happens only on iOS, Android is alright.

**To Reproduce**
```
await BleClient.initialize().then(() => {
     console.log('Client initialised');
});

const myBtDeviceID = '00:AA:BB:99:CC';

await BleClient.connect(myBtDeviceID);
console.log('Device connected');

setInterval(async () => {
     const connectedDevices = await BleClient.getConnectedDevices([GATT_SERVICE]);    
     for (const device of connectedDevices ) {
            if (device.deviceId.toUpperCase() === myBtDeviceID) {
                   console.log('device is connected');
                   return;
            }
     }
      console.log('device is not connected');
}, 5000);

await BleClient.startNotifications(device.id, this.WRITE_SERVICE, this.WRITE_CHARACTERISTIC, (packet) => {
        console.log('packet received', myParser(packet));
});
```

The message "packet received" is shown couple of times (2x - 5x) and than stops showing. Strange thing is If I remove the variable "GATT_SERVICE" from the getConnectedDevices argument (just provide empty array) everything is OK, BUT on iOS no connected devices are returned without the provided characteristic.

**Expected behavior**
Receiving all data from the bt device.

**Plugin version:**
- @capacitor-community/bluetooth-le 1.5.0

**Desktop (please complete the following information):**
- OS: macOS Big Sur

**Smartphone (please complete the following information):**
- Device: iPhone SE 2020
- OS: iOS 15

Thanks for checking this issue and thanks for this plugin!

**Comment by pwespi** [comment]
Does using the onDisconnect callback solve your issue?

**Comment by kozakhs** [comment]
> 
> 
> Does using the onDisconnect callback solve your issue?

Sorry for my delayed response. I am going to remake the app logic to not use the polling, but I havent did it yet. However lets suppose it will solve the issue, so I am closing this issue and if I encounter the problem again I wil create new one. Thank you very much.
