### ISSUE TITLE
Write with response request to return the response value

### ISSUE THREAD

**Issue by tozuro-it** [capacitor-community/bluetooth-le#226]
Hi,

Thanks again for creating and maintaining this plugin, it's great!

**Is your feature request related to a problem? Please describe.**
I've successfully used the plugin in a Capacitor-based test app and I've recently come across a possible limitation when writing to a characteristic using the 'write with response' method.
It seems that it is not currently possible to get the response value returned by a BLE device after a successful write request.

**Describe the solution you'd like**
Would it be possible to amend callbacks for 'write with response' methods to resolve with the value set on a characteristic?

I think this would require the following changes on Android, Device.kt file:
if-else block starting on line 127:
```kotlin
if (status == BluetoothGatt.GATT_SUCCESS) {
  resolve(key, "Characteristic successfully written.")
}
```
to be changed to:
```kotlin
if (status == BluetoothGatt.GATT_SUCCESS) {
  if ( characteristic.writeType == BluetoothGattCharacteristic.WRITE_TYPE_DEFAULT ) {
    val data = characteristic.value;
    var value = "";
    if ( data != null ) {
      value = bytesToString(data);
    }
    resolve(key, value)
  } else {
   resolve(key, "Characteristic successfully written.")
  }
}
```

Equivalent set of changes would be required on iOS side, Device.swift file, line 156 as well as Web, web.ts file, line 255.

The API entry for the write method would also require changing from:

```TypeScript
write(deviceId: string, service: string, characteristic: string, value: DataView): Promise<void>;
```

to something like this, I guess:
```TypeScript
write(deviceId: string, service: string, characteristic: string, value: DataView): Promise<DataView>;
```

and a new interface possibly getting added to definitions.ts file (based on `ReadResult`):

```TypeScript
export interface WriteResponseResult {
  /**
   * android, ios: string
   * web: DataView
   */
  value?: Data;
}
```

to be used in the `BluetoothLePlugin` interface for the `write(...)` function.

BleClient.ts, code starting at line 443 would also need to be changed to take into account the proposed changes.

**Describe alternatives you've considered**
I don't think any alternatives are possible for this use case.

**Additional context**
I only provided sample code for Android as I don't have access to Apple development environment and wasn't able to test my sample code on an iOS device.
A quick test on an Android device logged what seemed to be the expected results.

**Plugin version**
@capacitor-community/bluetooth-le: 1.5.0

Thank you in advance!

**Comment by pwespi** [comment]
Thank you for using this plugin and for this feature request. However I'm not sure if it's possible to implement on all platform.

In the [Apple Core Bluetooth](https://developer.apple.com/documentation/corebluetooth/cbcharacteristicwritetype) documentation, it says `Write a characteristic value, with a response from the peripheral to indicate whether the write was successful.` So the response is not about the value, but only whether the write was successful.

Also in Web Bluetooth, `writeValueWithResponse` returns a `Promise<void>`, so no value is coming back.

What prevents you from doing a `read` after the `write` to get the value?

**Comment by tozuro-it** [comment]
Hi,

My apologies for a late reply.

Thank you for checking and confirming that iOS and Web APIs don't support reading a value from a write-with-response request.

Reading after a successful write is a good suggestion. It's just in that particular case a BLE device vendor only supports a write operation for the characteristic I wanted to check the value for.

Thanks again for a really useful library! 

Closing this as it can't be implemented on all supported platforms.
