### ISSUE TITLE
Autoconnect for already known devices

### ISSUE THREAD

**Issue by thankthemaker** [capacitor-community/bluetooth-le#233]
Is it possible to implement autoconnect for a device that was searched via requestDevice before? 
I'd really like to avoid scanning for my device every time I start my app, it should connect automatically.

Is this already possible with this plugin?

**Comment by pwespi** [comment]
Yes, it should be possible. If you save the deviceId that you get from requestDevice in your first app run, you can then use [getDevices](https://github.com/capacitor-community/bluetooth-le#getdevices) with that deviceId to retrieve the device in subsequent app runs. If you're only using Android, you don't even have to use getDevices and can directly connect.

Is this what you were looking for?

**Comment by thankthemaker** [comment]
Yes, that's what I was looking for. I'll give it a try. Thank you.

**Comment by pwespi** [comment]
In case something does not work, let me know, and I will reopen this issue.
