### ISSUE TITLE
openAppSettings implem on Android

### ISSUE THREAD

**Issue by somq** [capacitor-community/bluetooth-le#237]
I'm developing a proprietary plugin which has many BLE features and get some of the inspiration from this plugin.
I noticed `openAppSettings` method is not implemented on Android though it's possible
So, for the reference if you wish to implement the feature, here is the code if someone wish to prepare a PR

openAppSettings  [implementation](https://github.com/capacitor-community/bluetooth-le/blob/main/android/src/main/java/com/capacitorjs/community/plugins/bluetoothle/BluetoothLe.kt#L192):
```kt
  @PluginMethod
  fun openAppSettings(call: PluginCall) {
    val intent = Intent(Settings.ACTION_APPLICATION_DETAILS_SETTINGS) // App details
    intent.data = Uri.parse("package:" + getActivity().getPackageName());
    getActivity().startActivity(intent);
  }
```

Cheers!

**Comment by pwespi** [comment]
Thank you very much. This has been added in #241.
