### ISSUE TITLE
X-code 13.1 and Swift Errors

### ISSUE THREAD

**Issue by aardrasystems** [capacitor-community/bluetooth-le#238]
Hi 

I have recently updated my Ios to Monterey 12.0.1, with Xcode 13.1.

My project is based on the Ionic Framework.

But when it preforms a build on Xcode I am getting swift error:

`Value of optional type 'CBService?' must be unwrapped to refer to member 'uuid' of wrapped base type 'CBService'
`

Is there a reason why this happens?

**Comment by pwespi** [comment]
Which version of the plugin are you using? This should be fixed in [v1.3.1](https://github.com/capacitor-community/bluetooth-le/blob/main/CHANGELOG.md#131-2021-09-22) and higher.

**Comment by aardrasystems** [comment]
Thanks, i just did an update and seems to solved the issue
