### ISSUE TITLE
Unhandled Promise Rejection on iOS Simulator

### ISSUE THREAD

**Issue by maelp** [capacitor-community/bluetooth-le#250]
**Describe the bug**
I'm just running `BLEClient.initialize().then(() => bleAvailable=true).catch(() => bleAvailable = false)`, it works on the web and on iOS device, but on the iOS simulator, the call fails, but it also generate this error, and then the whole app "hangs" (router doesn't work, etc)

![image](https://user-images.githubusercontent.com/15458/142857012-cafbbd11-8816-4308-b3c1-de254da8920f.png)

**To Reproduce**
1. Call the code above
2. Run it on the iOS simulator (I'm using iPhone 11, iOS 15)
3. Debug error using Safari > Develop > Simulator > (Choose your app)

**Expected behavior**
The initialize should just throw an error which is caught in the `.catch` and not have the application stop working correctly

**Plugin version:**
- @capacitor-community/bluetooth-le: latest

**Desktop (please complete the following information):**
- OS: osX
- iOS simulator (iPhone 11, iOS 15)

**Smartphone (please complete the following information):**

**Additional context**

**Comment by pwespi** [comment]
Thanks for using this plugin.

I cannot reproduce the behavior you're describing. Your line of code has a typo in `BleClient` and it's not clear what the variable `bleAvailable` is.

Please try the following:
```ts
BleClient.initialize()
  .then(() => {
    console.log("BLE available");
  })
  .catch(() => {
    console.log("BLE not available");
  });
```

With this code my app behaves as expected in the simulator and on the device.

**Comment by maelp** [comment]
My exact code is in VueJS and Ionic

```
import { BleClient } from '@capacitor-community/bluetooth-le';
import { ref, Ref } from 'vue';

export const bleAvailable = ref(false);
export const bleInitialized = ref(false);
export const bleError: Ref<any|undefined> = ref(undefined);

export async function initBLE() {
    if (bleInitialized.value) {
        return;
    }

    try {
        await BleClient.initialize();
        bleAvailable.value = true;
        bleError.value = undefined;
    } catch (error) {
        console.error("initBLE", error);
        bleAvailable.value = false;
        bleError.value = (error as any);
    } finally {
        bleInitialized.value = true
    }
}
```

**Comment by maelp** [comment]
Do you manage to have your code run on the iOS simulator?

**Comment by pwespi** [comment]
Yes, my code runs on the iOS simulator and logs `BLE not available`.

The error `TypeError: No default value` suggests that you might be using a variable before it has been given a value.

**Comment by pwespi** [comment]
Have you tried my code? Does it work?

**Comment by maelp** [comment]
Ok for some reason now the code works :)
Thanks
