### ISSUE TITLE
Add connect / disconnect listener

### ISSUE THREAD

**Issue by aanders77** [capacitor-community/bluetooth-le#259]
**Is your feature request related to a problem? Please describe.**
I would like to show a status message to the user, describing if BLE is connected or not.

**Describe the solution you'd like**
I want to be able to register a listener which can trigger an event whenever the specified device connects/disconnects.

**Describe alternatives you've considered**
I've considered to show the status message based on programatically triggered events (connect(), disconnect()), but it will not work when the device disconnects for other reasons (distance, empty battery, etc).

**Additional context**
Status message example:
![image](https://user-images.githubusercontent.com/9765529/146886991-ca8f559c-8b71-4313-b251-354021cb64c0.png)

**Comment by pwespi** [comment]
You can use the optional `onDisconnect` callback of the `connect` method.

E.g.
```ts
await BleClient.connect(device.deviceId, (deviceId) => {
  console.log(`device ${deviceId} disconnected`);
});
```

See https://github.com/capacitor-community/bluetooth-le#connect

**Comment by aanders77** [comment]
I didn't notice that argument, thanks!

tor. 23. des. 2021, 07:42 skrev pwespi ***@***.***>:
