### ISSUE TITLE
Bluetooth-le is not supported on Android

### ISSUE THREAD

**Issue by Bataino** [capacitor-community/bluetooth-le#269]
I'm working with ionic 4 and capacitor 3 and using remote debugging. Here is the error I get
![Screenshot 2022-01-07 001928](https://user-images.githubusercontent.com/66479955/148466378-80cd9ec9-4105-49c6-b1ba-b4c8c9974b75.png)

**Comment by pwespi** [comment]
Looks like the plugin is not correctly installed in your Android project. Please see https://capacitorjs.com/docs/android/troubleshooting#plugin-not-implemented and follow the steps there.

**Comment by pwespi** [comment]
I will close this as I don't think it is a problem with the plugin. Let me know if you don't agree.
