### ISSUE TITLE
BleClient.connect throws 'connection timeout' in 1.6.1

### ISSUE THREAD

**Issue by qpre** [capacitor-community/bluetooth-le#270]
**Describe the bug**
Hi,

when using 1.6.1, connect throws a connection timeout, even if connection succeeds.

**To Reproduce**
```
try {
   await BleClient.connect(
      ble_device_id,
      (device_id) => console.log('disconnected', device_id)
   );
} catch (e) {
   console.error(e); // throws 'Connection Timeout'
}

try {
   // works like a charm 
   const value = await BleClient.read(
     ble_device_id,
     SERVICE_UUID,
     CHARACTERISTIC_UUID
   );

   console.log(ip);
} catch (e) {
   console.error(e);
}
```

**Expected behavior**
the error should not be thrown if connection was a success

**Plugin version:**
- @capacitor-community/bluetooth-le: 1.6.1 

**Smartphone (please complete the following information):**
- Device: iPhone 11
- OS: 15.2

**Comment by qpre** [comment]
Turns out you need to stop scanning before you use BleClient.connect if you want to avoid the error.

**Comment by Benni77** [comment]
Hey Bro where did you get this information? Couldn't find anything about this. Is this based on try and error? Kinda experience something similar on my iPhone. 

> Turns out you need to stop scanning before you use BleClient.connect if you want to avoid the error.

✌️

**Comment by qpre** [comment]
Hello @Benni77, this was concluded from trial and errors.
