### ISSUE TITLE
Possible to get multiple notifications?

### ISSUE THREAD

**Issue by codeclinic** [capacitor-community/bluetooth-le#281]
Hi,

Apologies, for the question, but I don't see anywhere else/better to ask this.

Is it possible to get notification from multiple services or service characteristics?

If so, can this be done from a single `startNotifications()` or does it require a seperate 'startNotifications()' call for each?

Thanks.

**Comment by pwespi** [comment]
Yes, it is possible to get multiple notifications. You just call `startNotifications()` once per characteristic.

**Comment by codeclinic** [comment]
Thanks for the response and the work on this plugin.
