### ISSUE TITLE
Is finding nearby app users possible with this plugin?

### ISSUE THREAD

**Issue by jabi11** [capacitor-community/bluetooth-le#283]

**Comment by pwespi** [comment]
Not on its own. This plugin implements the central role of the Bluetooth Low Energy protocol. This means with this plugin you can scan for nearby devices. But you can only find devices that advertise. For your app to advertise, it needs to implement the peripheral role of Bluetooth Low Energy as well, which is not supported by this plugin. 

Plugins that support the peripheral role:
* https://github.com/randdusing/cordova-plugin-bluetoothle
* https://github.com/don/cordova-plugin-ble-peripheral

**Comment by pwespi** [comment]
related to https://github.com/capacitor-community/bluetooth-le/issues/292
