### ISSUE TITLE
Set Custom Connection Timeout

### ISSUE THREAD

**Issue by asangadev** [capacitor-community/bluetooth-le#296]
**Describe the bug**
I'm trying to set a custom connection timeout in my App. 

**To Reproduce**
```await BleClient.connect(deviceId, () => undefined, { timeout: 20000 })```

**Expected behavior**
20 seconds timeout and not the default 5 seconds

**Screenshots**
<img width="1160" alt="Screen Shot 2022-03-02 at 8 05 35 pm" src="https://user-images.githubusercontent.com/16328655/156329978-e7ae0ca9-263c-4ef2-8a73-d371da6efa87.png">

**Plugin version:**
- @capacitor-community/bluetooth-le: 1.8.0

**Smartphone (please complete the following information):**
- Device: iPhone 12 Pro
- OS: iOS 15.3.1
- Browser: N/A
- Version: N/A

**Additional context**
Not sure this is a bug or something to do with the way I'm calling that function? Thanks in advance!

**Comment by asangadev** [comment]
@pwespi thanks for the reply. Sorry yeah, you are right. Looks good with on connect. See attached. So how this `let timeout = self.getTimeout(call)` works in `startNotifications `?

Can we configure that timeout using the JS API (using options, the same way we configure the connect)? Please advise.

<img width="1079" alt="Screen Shot 2022-03-04 at 11 49 58 am" src="https://user-images.githubusercontent.com/16328655/156678296-4564607c-a10f-4d97-9e4e-cfc8530c4624.png">

**Comment by pwespi** [comment]
No, setting a custom timeout is not exposed for  `startNotifications`, only for calls like `read` and `write`. Do you run into timeout errors? In my experience, `startNotifications` is very fast. 

Note that `startNotifications` resolves after the subscription has been created, and the values can come any time later until `stopNotifications` is called. So the timeout only applies to the opening of the subscription, not to the transmission of values.

**Comment by asangadev** [comment]
@pwespi Thanks for the reply! This is very clear to me now. I will close this. Thanks again!
