### ISSUE TITLE
startNotifications for two devices only returns values of the last one

### ISSUE THREAD

**Issue by JasperFioole21** [capacitor-community/bluetooth-le#304]
**Describe the bug**
I created a method which loops over connected devices and starts a `startNotifications` for each of those. When I have two devices only notifications for the last device. 

Calling getConnectedDevices on iOS stops previous notification listeners.

**To Reproduce**
1. Connect 2 devices
2. Start notifications for both

**Expected behavior**
Receive notifications of both devices

**Screenshots**

**Plugin version:**
- @capacitor-community/bluetooth-le: 1.8.0

**Smartphone (please complete the following information):**
- Device: iPhone 13 pro
- OS:  iOS 15.3.1 (latest)

**Comment by pwespi** [comment]
Thank you for using this plugin.

I cannot reproduce this. Can you share some code that reproduces this behaviour?
