### ISSUE TITLE
BleClient.enable() causes OS bluetooth permission popup on Huawei phones and this is not handled

### ISSUE THREAD

**Issue by egeozer** [capacitor-community/bluetooth-le#311]
**Describe the bug**
The moment BleClient.enable() is called, a OS bluetooth permission popup "Allow app <app name> to enable bluetooth" appears on Huawei phones. Even before answering to the request, the .enable() has finished executing, however, BleClient.enable() should wait for user confirmation before calling the success callback, and call errorCallback if user denies permission to change bluetooth state.

This plugin: https://github.com/don/cordova-plugin-ble-central handles this case with an errorCallback if the user denies permission, so it waits for the user's response. However, I much prefer using this Capacitor plugin.

**To Reproduce**
1. On Huawei phone running on Android 9+
2. Call BleClient.enable()
3. An OS prompt will appear

**Expected behavior**
BleClient.enable() should wait for user confirmation before calling the success callback, and call errorCallback if user denies permission to change bluetooth state.

**Plugin version:**
- @capacitor-community/bluetooth-le: 1.8.0

**Smartphone (please complete the following information):**
- Device: Any Huawei model
- OS: [e.g. iOS8.1] Android 11

**Additional context**
Thanks!

**Comment by pwespi** [comment]
Sorry for the late reply!

v3.1.1 and v2.3.0 have just been released with a new method `requestEnable`, which fixes this. This new method has a similar implementation as the cordova-plugin-ble-central plugin you mentioned. The `enable` and `disable` methods are deprecated now.
