### ISSUE TITLE
iOS App connects to BLE peripheral on 1st attempt. Fails to find BLE peripheral on subsequent app launches / device scans

### ISSUE THREAD

**Issue by codeclinic** [capacitor-community/bluetooth-le#319]
I've built an iOS app using React & Ionic which connects to a BLE peripheral / GATT server device to read data etc. The app runs fine on the web in chrome, and works as expected when compiled as an Android app.

The iOS app compiles without issues and validates in App Connect. However, I'm having trouble connecting to the BLE peripheral from my iPad on iOS 15.4.1. The very first time I run the app on the iPad and scan for BLE devices it finds the peripheral and will connect. It only grabs some of the read requests that I make and then appears to disconnect.

If I try to reconnect by doing another scan it finds no devices. If I close and relaunch the app it still finds no devices. If, I turn off the iPad and the BLE peripheral before relaunching the app... still no devices found.

I've left both devices off for an hour or more and still its unable to find the device. I've even wiped the network and bluetooth settings from the iPad and it still doesn't work. I've uninstalled & re-installed the app, with no benefit. I even resorted to doing a full device reset of the iPad, reinstalled the app and tried again. This time a device scan in the app found the device and temporarily connected before being unable to find the device again.

Right now I'm really unsure as to what's happening and why.

**Comment by pwespi** [comment]
It's hard to say what is going on. Do you get any errors in Xcode? Have you tried scanning with another app (e.g. NRF connect) or the iOS Bluetooth settings?
