### ISSUE TITLE
BLE Device ID different on android and apple devices

### ISSUE THREAD

**Issue by aardrasystems** [capacitor-community/bluetooth-le#351]
Hi

I am trying to obtain the device id of the BLE module.

When I connect to the device using an Andriod device, I get the output in the following format:  AB:CD:EF:12:CD:EF, which is 6 hex bytes, but when I read the id using IOS device, the output is shown as the following"8957634D-85C0-0C2D-D410-01C37D02B51E"

Is there a reason why?

**Comment by pwespi** [comment]
I'm closing this as I don't think it's possible to have the same ID on all platforms.
