### ISSUE TITLE
BleClient.requestDevice case sensitivity issues on Android

### ISSUE THREAD

**Issue by ecc521** [capacitor-community/bluetooth-le#365]
Calling 
```
await BleClient.requestDevice({
    services: ['___lowercaseid___']
})
```

fails to find any devices on Android, while 
```
await BleClient.requestDevice({
    services: ['___lowercaseid___'.toUpperCase()]
})
```

succeeds. 

This is a significant difference from the web bluetooth API, which requires UUIDs to be lowercase, and throws if they are not. Additionally the sample UUID ```0000180d-0000-1000-8000-00805f9b34fb``` is lowercase, so lowercase UUIDs not working is highly confusing.

- I have tested this several times and the same behavior is occurring. That said, it is remotely possible that a series of fluke circumstances have occurred and there is not actually a bug here. As I have successfully connected multiple times with uppercase IDs, yet have not even detected a device with lowercase IDs, I find this incredibly unlikely. 

**Expected behavior**
Either UUIDs should be case insensitive, or requestDevice should throw if incorrect casing is passed. 

**Plugin version:**
- @capacitor-community/bluetooth-le: 1.8.2

**Desktop:**
macOS 12.4 Chrome

**Smartphone:**
OnePlus 7T HD1907, Android 11, Oxygen OS 11.0.8.1.HD65AA

**Additional context**
Phone connecting to an Arduino 33 BLE.

**Comment by pwespi** [comment]
Thank you for using this plugin. Unfortunately, I cannot reproduce this with my devices. For me both uppercase and lowercase works on Android. As you mentioned, could it be that some fluke circumstances have occurred?

**Comment by ecc521** [comment]
Based on further testing, it appears the initial behavior was not the result of a problem, and instead fluke circumstances.
