### ISSUE TITLE
@capacitor/core": "4.0.1" support

### ISSUE THREAD

**Issue by ASHBAW** [capacitor-community/bluetooth-le#377]
**Describe the bug**
Looks like there is no support for @capacitor/core 4.0.x?

**To Reproduce**
npm install @capacitor-community/bluetooth-le 

**Expected behavior**
it to install

**Plugin version:**
1.8.3

**Desktop (please complete the following information):**
macOS Monterey 12.5

**Additional context**
When you create a new ionic project (angular) it utilizes angular 14 and @capacitor/core version 4.0.1

```
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: ionic6_test@0.0.1
npm ERR! Found: @capacitor/core@4.0.1
npm ERR! node_modules/@capacitor/core
npm ERR!   @capacitor/core@"4.0.1" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer @capacitor/core@"^3.0.0" from @capacitor-community/bluetooth-le@1.8.3
npm ERR! node_modules/@capacitor-community/bluetooth-le
npm ERR!   @capacitor-community/bluetooth-le@"*" from the root project
```

**Comment by pwespi** [comment]
You can use the prerelease of the plugin V2:
```bash
npm i @capacitor-community/bluetooth-le@next
```

Will be closed by https://github.com/capacitor-community/bluetooth-le/pull/374
