### ISSUE TITLE
Possibility to connect without scanning before

### ISSUE THREAD

**Issue by treb93** [capacitor-community/bluetooth-le#383]
**Description**
When using [cordova-plugin-ble-central](https://github.com/don/cordova-plugin-ble-central), it's possible to connect using MAC address  without scanning on Android. (see [related documentation](https://github.com/don/cordova-plugin-ble-central#scanning-before-connecting))

Is it possible to implement this feature ? I guess it might reduce latency and help to strengthen the connection process

**Comment by pwespi** [comment]
This is already possible. As mentioned [here](https://github.com/capacitor-community/bluetooth-le#bledevice), the deviceId is the Bluetooth MAC address on Android. If you already know it, you can directly call `connect` with it. However, this is only possible on Android and not on iOS nor web.
