### ISSUE TITLE
implement getDevices() for android and ios

### ISSUE THREAD

**Issue by jrobeson** [capacitor-community/bluetooth-le#4]
**Is your feature request related to a problem? Please describe.**
It doesn't seem possible to get multiple devices to interact with them. 
`requestDevice()` will never return a single result for my usecases.

EDIT: after rereading the spec, it might make more sense to leave `getDevices` as is, and rather add a new method called `requestDevices()` which takes the same filter args as `requestDevice` or alternatively, add a new set of functions that more closely aligns with other existing bluetooth modules/plugins like a scan function that return an observable or operate on a callback.

**Comment by pwespi** [comment]
Thank you for using this plugin and for submitting this feature request.

It is already possible to call `requestDevice()` more than once and store the results, then you can interact with several devices at the same time.

But I assume you would prefer a single `scan` function (or similar) and get all discovered devices in a callback? Would you mind describing your use case in more detail? This would help me design this feature. Thanks.

**Comment by jrobeson** [comment]
You can? The Examples weren't clear about that, but how does it work if you have multiple devices with the same name offering the same services? The spec didn't seem to clearly say how you'd disambiguate in that situation.  There'd no such ambiguity by implementing `getDevices()`

**Comment by pwespi** [comment]
I released a new version of the plugin which has [requestLEScan](https://github.com/capacitor-community/bluetooth-le#requestlescan) and [stopLEScan](https://github.com/capacitor-community/bluetooth-le#stoplescan).
