### ISSUE TITLE
Updating iOS native dependencies with pod install - failed!

### ISSUE THREAD

**Issue by pixxlefr** [capacitor-community/bluetooth-le#402]
Hello
Hello everyone,

I try to add the ios platform in my ionic project with capacitor but I have this error:

✔ Copying web assets from www to ios/App/App/public in 1.12s
✔ Creating capacitor.config.json in ios/App/App in 2.02ms
✔ copy ios in 1.14s
✔ Updating iOS plugins in 6.91ms
[info] Found 5 Capacitor plugins for ios:
       @capacitor-community/bluetooth-le@2.0.0
       @capacitor/app@4.0.1
       @capacitor/haptics@4.0.1
       @capacitor/keyboard@4.0.1
       @capacitor/status-bar@4.0.1
✖ Updating iOS native dependencies with pod install - failed!
✖ update ios - failed!
[error] ERR_SUBPROCESS_COMMAND_NOT_FOUND
But for Android it’s work perfectly!

Do you have an idea for why I have this error?

Thanks

**Comment by pwespi** [comment]
Do you have cocoapods installed?
https://capacitorjs.com/docs/getting-started/environment-setup#cocoapods

Does it work in a new Capacitor app without any plugins installed?
