### ISSUE TITLE
Error: Characteristic Not Found. 

### ISSUE THREAD

**Issue by mkanjipuram** [capacitor-community/bluetooth-le#442]
import { BleClient } from '@capacitor-community/bluetooth-le';
await BleClient.initialize({ androidNeverForLocation: true });
//This is the setup I am using. 

async connectDevice(){
  await BleClient.connect(device.deviceId).then(result => {
    alert(result) //This returns undefined. 
  }
.catch(err => {
    alert(err) //The function does not land here. 
  });
}

**### Questions:
1. Does BleClient.connect does not retrun a promise? Is undefined okay as shown above? 
2. When I try to call another function to write and/or writeWithoutResponse, it returns me the error in catch block "Characterstic Not Found".**

I have double checked the SERVICE UUID and CHARACTERSTIC UUID, and they match both on my ESP32 Dev C3 board and my mobile app code. 

I have also ensured that the ESP32 Dev C3 has the esp32 server and write codes setup done. please see below for reference. 

/*
    Based on Neil Kolban example for IDF: https://github.com/nkolban/esp32-snippets/blob/master/cpp_utils/tests/BLE%20Tests/SampleWrite.cpp
    Ported to Arduino ESP32 by Evandro Copercini
*/

#include <BLEDevice.h>
#include <BLEUtils.h>
#include <BLEServer.h>

// See the following for generating UUIDs:
// https://www.uuidgenerator.net/

#define SERVICE_UUID        "4fafc201-1fb5-459e-8fcc-c5c9c331914b"
#define CHARACTERISTIC_UUID "beb5483e-36e1-4688-b7f5-ea07361b26a8"

class MyCallbacks: public BLECharacteristicCallbacks {
    void onWrite(BLECharacteristic *pCharacteristic) {
      std::string value = pCharacteristic->getValue();

      if (value.length() > 0) {
        Serial.println("*********");
        Serial.print("New value: ");
        for (int i = 0; i < value.length(); i++)
          Serial.print(value[i]);

        Serial.println();
        Serial.println("*********");
      }
    }
};

void setup() {
  Serial.begin(115200);

  Serial.println("1- Download and install an BLE scanner app in your phone");
  Serial.println("2- Scan for BLE devices in the app");
  Serial.println("3- Connect to MyESP32");
  Serial.println("4- Go to CUSTOM CHARACTERISTIC in CUSTOM SERVICE and write something");
  Serial.println("5- See the magic =)");

  BLEDevice::init("MyESP32");
  BLEServer *pServer = BLEDevice::createServer();

  BLEService *pService = pServer->createService(SERVICE_UUID);

  BLECharacteristic *pCharacteristic = pService->createCharacteristic(
                                         CHARACTERISTIC_UUID,
                                         BLECharacteristic::PROPERTY_READ |
                                         BLECharacteristic::PROPERTY_WRITE
                                       );

  pCharacteristic->setCallbacks(new MyCallbacks());

  pCharacteristic->setValue("Hello World");
  pService->start();

  BLEAdvertising *pAdvertising = pServer->getAdvertising();
  pAdvertising->start();
}

void loop() {
  // put your main code here, to run repeatedly:
  delay(2000);
}

**Comment by pwespi** [comment]
> Does BleClient.connect does not retrun a promise? Is undefined okay as shown above?

The `connect` call returns a `Promise<void>` which means that the promise does not return a value. So yes, `undefined` is correct in that location.

> When I try to call another function to write and/or writeWithoutResponse, it returns me the error in catch block "Characterstic Not Found".**

Can you check with the [`getServices`](https://github.com/capacitor-community/bluetooth-le#getservices) method whether your peripheral really offers the service / characteristic you're trying to use. Alternatively you can use other apps such as [nRF Connect](https://play.google.com/store/apps/details?id=no.nordicsemi.android.mcp) to check whether your peripheral correctly offers the service / characteristic you're trying to use.
