### ISSUE TITLE
ios app disconnects from device after almost 5-8s after connecting.

### ISSUE THREAD

**Issue by Thilakforabm** [capacitor-community/bluetooth-le#464]
Hi,
Thank you for the awesome plugin,
I have built an app for ios , and after the device connects to the peripoheral device it disconnects after about 5-8s
the app seem to be working fine in ios,
this is my first time working ionic so im sorry if im being vague
there is an xpc connection invalid error from the xcode log below , which im not entirely sure is the issue
on the peripheral device it raises an error saying the connection was reset by peer.

2022-12-23 12:16:45.657992+0530 App[3698:369767] [SceneConfiguration] Info.plist contained no UIScene configuration dictionary (looking for configuration named "(no name)")
2022-12-23 12:16:45.658027+0530 App[3698:369767] [SceneConfiguration] Info.plist contained no UIScene configuration dictionary (looking for configuration named "(no name)")
2022-12-23 12:16:45.658053+0530 App[3698:369767] [SceneConfiguration] Info.plist contained no UIScene configuration dictionary (looking for configuration named "(no name)")
2022-12-23 12:16:45.732344+0530 App[3698:369767] KeyboardPlugin: resize mode - native
⚡️  Loading app at capacitor://localhost...
⚡️  WebView loaded
⚡️  To Native ->  BluetoothLe initialize 111682784
Resolve initialize BLE powered on
⚡️  TO JS undefined
⚡️  To Native ->  BluetoothLe addListener 111682785
⚡️  To Native ->  BluetoothLe startEnabledNotifications 111682786
⚡️  TO JS undefined
⚡️  To Native ->  App addListener 111682787
SplashScreen.hideSplash: SplashScreen was automatically hidden after default timeout. You should call `SplashScreen.hide()` as soon as your web app is loaded (or increase the timeout). Read more at https://capacitorjs.com/docs/apis/splash-screen#hiding-the-splash-screen
⚡️  To Native ->  BluetoothLe isEnabled 111682788
⚡️  TO JS {"value":true}
⚡️  To Native ->  BluetoothLe isLocationEnabled 111682789
ERROR MESSAGE:  {"errorMessage":"isLocationEnabled is not available on iOS.","message":"isLocationEnabled is not available on iOS.","code":"UNAVAILABLE"}
⚡️  [error] - {"errorMessage":"isLocationEnabled is not available on iOS.","message":"isLocationEnabled is not available on iOS.","code":"UNAVAILABLE"}
⚡️  [log] - Error in checking location
⚡️  To Native ->  BluetoothLe addListener 111682790
⚡️  To Native ->  BluetoothLe requestLEScan 111682791
Resolve startScanning Scan started.
⚡️  TO JS undefined
New device found:  ABM Device-A019
⚡️  TO JS {"uuids":["0000180d-0000-1000-8000-00805f9b34fb"],"device":{"name":"ABM Device-A019","deviceId":"A2E01DF4-1106-1577-5EDF-D461648D104A"},"localName":"ABM Device-A019","rssi":-73,"txPower":14}
⚡️  [error] - Clicked A2E01DF4-1106-1577-5EDF-D461648D104A
⚡️  [log] -  help11111111 A2E01DF4-1106-1577-5EDF-D461648D104A
⚡️  To Native ->  BluetoothLe addListener 111682792
⚡️  To Native ->  BluetoothLe connect 111682793
Connecting to peripheral <CBPeripheral: 0x2824400d0, identifier = A2E01DF4-1106-1577-5EDF-D461648D104A, name = ABM Device-A019, mtu = 0, state = disconnected>
Connected to device <CBPeripheral: 0x2824400d0, identifier = A2E01DF4-1106-1577-5EDF-D461648D104A, name = ABM Device-A019, mtu = 23, state = connected>
Resolve connect|A2E01DF4-1106-1577-5EDF-D461648D104A Successfully connected.
Connected to peripheral. Waiting for service discovery.
didDiscoverServices
didDiscoverCharacteristicsFor 1 1
Resolve connect Connection successful.
⚡️  TO JS undefined
⚡️  [log] - Connection Successful. undefined
⚡️  To Native ->  BluetoothLe getServices 111682794
⚡️  TO JS {"services":[{"characteristics":[{"properties":{"notify":true,"writeWithoutResponse":false,"notifyEncryptionRequired":false,"write":true,"indicate":false,"read":true,"extendedProperties":false,"indicateEncryptionRequired":false,"authenticatedSignedWrites":
⚡️  [log] - blessertffffffffff [{"characteristics":[{"properties":{"notify":true,"writeWithoutResponse":false,"notifyEncryptionRequired":false,"write":true,"indicate":false,"read":true,"extendedProperties":false,"indicateEncryptionRequired":false,"authenticatedSignedWrites":false,"broadcast":false},"descriptors":[{"uuid":"00002902-0000-1000-8000-00805f9b34fb"}],"uuid":"00002a37-0000-1000-8000-00805f9b34fb"}],"uuid":"0000180d-0000-1000-8000-00805f9b34fb"}]
⚡️  [error] - .......Subscribing
⚡️  To Native ->  BluetoothLe initialize 111682795
Resolve initialize BLE powered on
⚡️  TO JS undefined
⚡️  To Native ->  BluetoothLe stopNotifications 111682796
Set notifications false
Resolve setNotifications|0000180D-0000-1000-8000-00805F9B34FB|00002A37-0000-1000-8000-00805F9B34FB Successfully set notifications.
⚡️  TO JS undefined
⚡️  To Native ->  BluetoothLe addListener 111682797
⚡️  To Native ->  BluetoothLe startNotifications 111682798
Set notifications true
Resolve setNotifications|0000180D-0000-1000-8000-00805F9B34FB|00002A37-0000-1000-8000-00805F9B34FB Successfully set notifications.
⚡️  TO JS undefined
Resolve callback not registered for key:  read|0000180D-0000-1000-8000-00805F9B34FB|00002A37-0000-1000-8000-00805F9B34FB
⚡️  TO JS {"value":"70 6f 66 69 6c 65 4e 61 6d 65 41 75 74 6f "}
Resolve callback not registered for key:  read|0000180D-0000-1000-8000-00805F9B34FB|00002A37-0000-1000-8000-00805F9B34FB
⚡️  TO JS {"value":"70 6c 61 79 53 74 61 74 65 74 72 75 65 "}
⚡️  To Native ->  BluetoothLe removeListener 111682799
⚡️  [error] - Start Notification: PASS
⚡️  [error] - Subscribed to Notifications
⚡️  To Native ->  BluetoothLe stopLEScan 111682800
Stop scanning.
⚡️  TO JS undefined
⚡️
⚡️  To Native ->  BluetoothLe write 111682801
⚡️  [log] - stopped scanning
Resolve write|0000180D-0000-1000-8000-00805F9B34FB|00002A37-0000-1000-8000-00805F9B34FB Successfully written value.
⚡️  TO JS undefined
Resolve callback not registered for key:  read|0000180D-0000-1000-8000-00805F9B34FB|00002A37-0000-1000-8000-00805F9B34FB
⚡️  TO JS {"value":"73 79 6e 63 5f 74 69 6d 65 2c 30 "}
Resolve callback not registered for key:  read|0000180D-0000-1000-8000-00805F9B34FB|00002A37-0000-1000-8000-00805F9B34FB
⚡️  TO JS {"value":"70 6f 66 69 6c 65 4e 61 6d 65 41 75 74 6f "}
Resolve callback not registered for key:  read|0000180D-0000-1000-8000-00805F9B34FB|00002A37-0000-1000-8000-00805F9B34FB
⚡️  TO JS {"value":"52 69 62 62 6f 6e 5f 73 74 61 74 65 74 72 75 65 "}
⚡️  To Native ->  BluetoothLe initialize 111682802
2022-12-23 12:16:59.867260+0530 App[3698:370000] [CoreBluetooth] XPC connection invalid
Resolve initialize BLE powered on
⚡️  TO JS undefined
⚡️ 
⚡️  To Native ->  BluetoothLe initialize 111682803
2022-12-23 12:16:59.887577+0530 App[3698:370000] [CoreBluetooth] XPC connection invalid
Resolve initialize BLE powered on
⚡️  TO JS undefined
⚡️  To Native ->  BluetoothLe initialize 111682804
2022-12-23 12:16:59.900841+0530 App[3698:370001] [CoreBluetooth] XPC connection invalid
Resolve initialize BLE powered on
⚡️  TO JS undefined
⚡️  To Native ->  BluetoothLe initialize 111682805
2022-12-23 12:16:59.908068+0530 App[3698:370001] [CoreBluetooth] XPC connection invalid
Resolve initialize BLE powered on
⚡️  TO JS undefined
⚡️  To Native ->  BluetoothLe initialize 111682806
2022-12-23 12:16:59.912131+0530 App[3698:370001] [CoreBluetooth] XPC connection invalid
Resolve initialize BLE powered on
⚡️  TO JS undefined
⚡️  To Native ->  BluetoothLe initialize 111682807
2022-12-23 12:16:59.916812+0530 App[3698:370001] [CoreBluetooth] XPC connection invalid
Resolve initialize BLE powered on
⚡️  TO JS undefined
⚡️  To Native ->  BluetoothLe initialize 111682808
2022-12-23 12:16:59.920021+0530 App[3698:370001] [CoreBluetooth] XPC connection invalid
Resolve initialize BLE powered on
⚡️  TO JS undefined
⚡️  To Native ->  BluetoothLe initialize 111682809
2022-12-23 12:16:59.922949+0530 App[3698:370001] [CoreBluetooth] XPC connection invalid
Resolve initialize BLE powered on
⚡️  TO JS undefined
Resolve callback not registered for key:  read|0000180D-0000-1000-8000-00805F9B34FB|00002A37-0000-1000-8000-00805F9B34FB
⚡️  TO JS {"value":"52 69 62 62 6f 6e 5f 73 74 61 74 65 74 72 75 65 "}
⚡️Resolve callback not registered for key:  read|0000180D-0000-1000-8000-00805F9B34FB|00002A37-0000-1000-8000-00805F9B34FB
⚡️  TO JS {"value":"52 69 62 62 6f 6e 5f 73 74 61 74 65 74 72 75 65 "}
⚡️  Resolve callback not registered for key:  read|0000180D-0000-1000-8000-00805F9B34FB|00002A37-0000-1000-8000-00805F9B34FB
⚡️  TO JS {"value":"52 69 62 62 6f 6e 5f 73 74 61 74 65 66 61 6c 73 65 "}
⚡️ 
⚡️  To Native ->  BluetoothLe initialize 111682810
2022-12-23 12:17:01.910769+0530 App[3698:370001] [CoreBluetooth] XPC connection invalid
Resolve initialize BLE powered on
⚡️  TO JS undefined
Resolve callback not registered for key:  read|0000180D-0000-1000-8000-00805F9B34FB|00002A37-0000-1000-8000-00805F9B34FB
⚡️  TO JS {"value":"52 69 62 62 6f 6e 5f 73 74 61 74 65 66 61 6c 73 65 "}
⚡️  
⚡️  To Native ->  BluetoothLe initialize 111682811
2022-12-23 12:17:02.386831+0530 App[3698:370001] [CoreBluetooth] XPC connection invalid
Resolve initialize BLE powered on
⚡️  TO JS undefined
Resolve callback not registered for key:  read|0000180D-0000-1000-8000-00805F9B34FB|00002A37-0000-1000-8000-00805F9B34FB
⚡️  TO JS {"value":"52 69 62 62 6f 6e 5f 73 74 61 74 65 66 61 6c 73 65 "}
⚡️  
Resolve callback not registered for key:  read|0000180D-0000-1000-8000-00805F9B34FB|00002A37-0000-1000-8000-00805F9B34FB
⚡️  TO JS {"value":"52 69 62 62 6f 6e 5f 73 74 61 74 65 66 61 6c 73 65 "}
⚡️  Resolve callback not registered for key:  read|0000180D-0000-1000-8000-00805F9B34FB|00002A37-0000-1000-8000-00805F9B34FB
⚡️  TO JS {"value":"52 69 62 62 6f 6e 5f 73 74 61 74 65 66 61 6c 73 65 "}
2022-12-23 12:17:06.129059+0530 App[3698:370000] [CoreBluetooth] XPC connection invalid

would very much appreciate any feedback

**Comment by pwespi** [comment]
Thank you for using this plugin.

I'm not sure if this is the issue, but from your logs it looks like you're calling `initialize` a lot. It is recommended to only call it once.

Can you try again with only one initialize call?
