### ISSUE TITLE
Custom "Service and Characteristics" creation

### ISSUE THREAD

**Issue by WildChildForLife** [capacitor-community/bluetooth-le#475]
**Is your feature request related to a problem? Please describe.**
My aim is to create a Web Application that can exchange data between different devices using Bluetooth. I learned that we can create custom Services & Characteristics that can hold the payload. Not impossible today with the current version according to what can be found on the documentation. 

**Describe the solution you'd like**
Methods binded with the Web API that will help create custom Service and its underlaying Characteristics for a specific device. GATT for example when it does not exist.

Thanks.

**Comment by pwespi** [comment]
Bluetooth Low Energy connections require one device to have the central role and the other to have the peripheral role. This plugin only supports the central role, as stated in the documentation.

While iOS and Android would support the peripheral role, it is not planned to be implemented in this plugin. The Bluetooth Web API does not support the peripheral role, so for web it's not event possible to implement. Therefore I'll have to close this feature request.
