### ISSUE TITLE
requestDevice not working without dialogbox (showdialog = false)

### ISSUE THREAD

**Issue by gregoiregentil** [capacitor-community/bluetooth-le#518]
In version 2.2.0 or earlier, I would like to use requestDevice without showing the dialog box (and de facto selecting the first device that matches my criteria).

So I change showDialog = false on this line: https://github.com/capacitor-community/bluetooth-le/blob/main/android/src/main/java/com/capacitorjs/community/plugins/bluetoothle/BluetoothLe.kt#L293

But then, it's not working. I have to patch the following:

```
--- node_modules/@capacitor-community/bluetooth-le/android/src/main/java/com/capacitorjs/community/plugins/bluetoothle/DeviceScanner.kt	2023-04-07 17:21:14.954956599 -0700
+++ node_modules/@capacitor-community/bluetooth-le/android/src/main/java/com/capacitorjs/community/plugins/bluetoothle/DeviceScanner.kt	2023-04-07 17:24:55.749245428 -0700
@@ -69,7 +69,8 @@
                 }
             } else {
                 if (allowDuplicates || isNew) {
-                    scanResultCallback?.invoke(result)
+                  savedCallback?.invoke(ScanResponse(true, result.device.address, result.device))
+                  savedCallback = null
                 }
             }
         }
@@ -98,7 +99,7 @@
             if (showDialog) {
                 dialogHandler = Handler(Looper.getMainLooper())
                 showDeviceList()
-            } else {
+            } else if (scanResultCallback != null) {
                 savedCallback?.invoke(
                     ScanResponse(
                         true, "Started scanning.", null
```

Clearly the first hunk was totally wrong before my patch. The second hunk leverages the fact that scanResultCallback is null for requestDevice.

You probably didn't test this scenario as showDialog is not exposed. Could you fix the same problem on iOS too? Would you be OK to expose showDialog on the web interface of requestDevice?

**Comment by pwespi** [comment]
If you don't want to show a dialog, you should use `requestLEScan`. For your use case, you can just use the first scan result you get from requestLEScan and then call stopLEScan.

The two methods requestDevice and requestLEScan are modeled after the Web Bluetooth API, where requestDevice shows a dialog for the user to pick a device and requestLEScan returns the scan results in a callback function.

> Would you be OK to expose showDialog on the web interface of requestDevice? 

This is not possible, as there is no showDialog API in requestDevice of the Web Bluetooth API. The dialog is always shown. The showDialog flag in the Android code was never meant to be exposed. It's only there to be able to reuse code internally in the plugin.

Your patch actually breaks the requestLEScan method, so you might want to revert it to use requestLEScan.
