### ISSUE TITLE
Remove throat to remove CommonJS dependency

### ISSUE THREAD

**Issue by aadito123** [capacitor-community/bluetooth-le#520]
**Is your feature request related to a problem? Please describe.**
Most build tools always give a warning for this package because it has a dependency on throat, which is a CommonJS module. The functionality provided by the library is also quite minimal.

**Describe the solution you'd like**
Just replace throat with normal promise chaining to mimic the queuing.

**Describe alternatives you've considered**
None.

**Additional context**
Included a PR for your consideration as well.

**Comment by pwespi** [comment]
closed by #521
