### ISSUE TITLE
IOS connection error

### ISSUE THREAD

**Issue by CasperQuitzau** [capacitor-community/bluetooth-le#530]
**Describe the bug**
I am developing an app for Android and iPhone in Ionic/Angular using this add-on to connect to an iTAG beacon with a button on it.
Like this: https://gadgetmou.com/product/smart-bluetooth-mini-waterproof-wireless-itag-alarm-tracer-gps-locator-alarm-anti-lost/
Android connects fine and is able to scan and connect to the device.
IOS can scan and find the device, but when asked to connect it get immediately disconnected with an error 

Please keep in mind that i am rather new to Angular/TypeScript ;-)

**To Reproduce**
1. Scan for devices
2. connect to the device using MAC address
3. Works on Android but fails on IOS
4. the following error appears in xCode:
```
...
 [log] - BLE STATUS:  Connecting to device "F470B536-6ABF-F58D-F1D6-E43AB8B43B87"
⚡️  BluetoothLe - Connecting to peripheral <CBPeripheral: 0x283a47b60, identifier = F470B536-6ABF-F58D-F1D6-E43AB8B43B87, name = iTAG            , mtu = 23, state = disconnected>
⚡️  BluetoothLe - Reject connect Connection timeout
ERROR MESSAGE:  {"message":"Connection timeout","errorMessage":"Connection timeout"}
⚡️  [error] - {"message":"Connection timeout","errorMessage":"Connection timeout"}
⚡️  To Native ->  BluetoothLe initialize 86048855
⚡️  [log] - BLE STATUS:  ERROR! Error while connecting to device "iTAG connect error: Error - Connection timeout"
⚡️  BluetoothLe - Resolve initialize BLE powered on 
...
```

**Plugin version:**
```
npm view capacitor-community/bluetooth-le       
@capacitor-community/bluetooth-le@3.0.0-1 | MIT | deps: 1 | versions: 1
Capacitor plugin for Bluetooth Low Energy 
dist
.tarball: file:git+ssh://git@github.com/capacitor-community/bluetooth-le.git#b421d2937ff840e71723d19ceef0dc479f599a2d
.shasum: undefined
dependencies:
@types/web-bluetooth: ^0.0.16 
dist-tags:
latest: 3.0.0-1 
```
**Desktop (please complete the following information):**
- Windows 10
- Visual Studio Code
```
npm -v
9.5.0
```
```
ionic -v
5.4.16
```
```
node -v        
v18.15.0
```
Please notice that i am developing on a windows 10 computer, but the project is cloned via git to a Mac when transferring the app to an iPhone

**Smartphone (please complete the following information):**
- OS: IOS 15.7
- iPhone 6s

**TypeScrip code**
The connect function that throws the error:
```
    /**
     * Connect to iTag device and start listening for notifications
     * @param deviceID 
     * @param bondDevice 
     * @param notificationCallback 
     * @param successCallback 
     * @param errorCallback 
     * @param disconnectCallback 
     * @param stateChangeCallback 
     */
    public async itagConnect(
        deviceID: string = "",
        bondDevice = false,
        successCallback: CallableFunction = this.onSuccess,
        errorCallback: CallableFunction = this.onError,
        disconnectCallback: CallableFunction = this.onDisconnect,
        stateChangeCallback: CallableFunction = this.onStateChange
    ): Promise<void> {

        try {            
            // Connect device
            this.onStatusUpdate("Connecting to device \""+deviceID+"\"");
            await BleClient.connect(
                deviceID, 
                () => {
                    disconnectCallback();
                },
                {timeout: 10000}
            ).then(
                () => {
                    //Keep bluetooth connection alive by reading device battery level
                    this.onStatusUpdate("Start monitoring battery level")
                    this.batteryMonitor = setInterval(() => {
                        if (this.bluetoothConnectedDevice.length == 0 || this.bluetoothIsScanning) {
                            clearInterval(this.batteryMonitor);
                        } else {
                            this.ReadBatteryLevel(deviceID);
                        }
                    }, 1000);
                    this.onStatusUpdate("Connection successfull");
                }
            )   

            //Bond/pair device to phone (Android only!)
            if (bondDevice) {
                this.onStatusUpdate("Bonding with device")
                if (!BleClient.isBonded(deviceID)) {
                    BleClient.createBond(deviceID);
                }
            } else {
                this.onStatusUpdate("Bonding is disabled")
            }


            // Monitor for bluetooth state change
            this.onStatusUpdate("Start bluetooth state monitoring")
            BleClient.startEnabledNotifications(
                (value: boolean) => {
                    stateChangeCallback(value);
                }
            )

            // If no errors, call success callback function
            this.connected = true;
            this.bluetoothScanResults = [];
            successCallback()
        } catch (error) {
            // BLE connecton failed
            errorCallback("iTAG connect error: "+error.name+" - "+error.message)
        }
    }
```

**Comment by pwespi** [comment]
Can you connect to the iTAG with another app such as nRF Connect for Mobile?

**Comment by CasperQuitzau** [comment]
I have tested with two different kind/versions of iTAG's. One with Bluetooth 4.2 and one with 5.0.
It is unclear why but other app can connect to the 4.2 bluetooth device with eg. nRF connect, but not the 5.0 version. Might have something to do with the age of the phone.

But... none of the devices is able to connect via my Ionic app, and returns the same error as posted. Both device has no probelms connecting to my Android device (OnePlus 8Pro)

**Comment by pwespi** [comment]
Have you found out anything by testing with more devices?

**Comment by CasperQuitzau** [comment]
Finally we got a newer iPhone to test on, but the result is still the same.
It is an iPhone SE with iOS 16.4, and we have updated iOS and xCode accordingly on the development Mac-book.

```
⚡️  Native ->  BluetoothLe initialize 28948423
⚡️  BluetoothLe - Resolve initialize BLE powered on
⚡️  TO JS undefined
⚡️  To Native ->  BluetoothLe getConnectedDevices 28948424
⚡️  TO JS {"devices":[]}
⚡️  To Native ->  BluetoothLe
⚡️  [log] - BLE STATUS:  Attempting to connect to device "59353DDC-DACC-D596-F0EC-CFB22B9000DC"
removeListener 28948425
⚡️  [log] - BLE STATUS:  Connecting to device "59353DDC-DACC-D596-F0EC-CFB22B9000DC"
⚡️  To Native ->  BluetoothLe addListener 28948426
⚡️  To Native ->  BluetoothLe connect 28948427
⚡️  BluetoothLe - Connecting to peripheral <CBPeripheral: 0x280e27740, identifier = 59353DDC-DACC-D596-F0EC-CFB22B9000DC, name = iTAG            , mtu = 23, state = disconnecting>
⚡️  BluetoothLe - Reject connect Connection timeout
ERROR MESSAGE:  {"errorMessage":"Connection timeout","message":"Connection timeout"}
⚡️  [error] - {"errorMessage":"Connection timeout","message":"Connection timeout"}
⚡️  [log] - BLE STATUS:  ERROR! Error while connecting to device "iTAG coneect error: Error - Connection timeout"
⚡️  To Native ->  BluetoothLe initialize 28948428
⚡️  BluetoothLe - Resolve initialize BLE powered on
⚡️  TO JS undefined
⚡️  To Native ->  BluetoothLe getConnectedDevices 28948429
⚡️  TO JS {"devices":[]}
2023-05-17 10:31:05.232793+0200 App[634:18510] [Snapshotting] Snapshotting a view (0x10182ee00, UIKeyboardImpl) that is not in a visible window requires afterScreenUpdates:YES.
```

**Comment by pwespi** [comment]
Have you tried increasing the timeout? https://github.com/capacitor-community/bluetooth-le#connect

If other apps also fail to connect to it, it could be that it is somehow blocked by the OS. But I don't have experience with iTags.

**Comment by CasperQuitzau** [comment]
The connect timeout is set to 10 seconds which should be more than enough, but the disconnect comes almost instantly after the connection has been initiated.
I know that it for a very short moment has a connection to the iTAG, be course after the iPhone/xCode shows the disconnect message in the log the iTAG will start beep'ing as a result of a lost cennection.
This makes be come to the conclusion that is is the iPhone that drops the connection for some reason. And before my code can start reading batterylevel.

An older iPhone 6S had problems with the Bluetooth 5.0 device, but the newer iPhone SE and an iPad running the same iOS as the old iPhone have no problems in connection to both the Bluetooth 4.2 and 5.0 device (Both branded as iTAG's)
IT is only the "connect" statement as showed in my example code that fails to connect on IOS.


If you have any code examples that successfully connects and listens to an iTAG (regardless of Bluetooth version) on iOS i would be very interested in seeing it.

**Comment by CasperQuitzau** [comment]
I wonder why the connection log show the state "disconnecting" in the same line as the connect statement itself:
`
BluetoothLe - Connecting to peripheral <CBPeripheral: 0x280e27740, identifier = 59353DDC-DACC-D596-F0EC-CFB22B9000DC, name = iTAG            , mtu = 23, state = disconnecting>
`

It is as if the device is told to disconnect as soon as the connection is made?

**Comment by pwespi** [comment]
Version 3.1.0 contains a possible fix for this issue. Can you check if it solves your problem.
