### ISSUE TITLE
Writing characteristic failed

### ISSUE THREAD

**Issue by dmsuh** [capacitor-community/bluetooth-le#540]
### Discussed in https://github.com/capacitor-community/bluetooth-le/discussions/538

<div type='discussions-op-text'>

<sup>Originally posted by **dmsuh** May 11, 2023</sup>
![image](https://github.com/capacitor-community/bluetooth-le/assets/90576894/8aee0b5f-be60-4488-9d85-84aba10941f3)
I'm recording according to the rules. But nothing works out.
![image](https://github.com/capacitor-community/bluetooth-le/assets/90576894/2a3a92d8-e511-4dcd-bb3d-26092005eb38)
This entry has a code to restore to factory settings
![image](https://github.com/capacitor-community/bluetooth-le/assets/90576894/197f9bd6-29f2-4500-9bb2-cf8c43ce565c)
The test program outputs the result perfectly</div>

**Comment by pwespi** [comment]
Closing to not duplicate the discussion from #538
