### ISSUE TITLE
createBond() failing on Android 10

### ISSUE THREAD

**Issue by maguirre-tribalyte** [capacitor-community/bluetooth-le#546]
When I call `createBond()` on Android 10 it fails with "Creating bond Failed" on the ADB logcat. Am I missing some step to make it work? 

1. Request Device on android 10
2. Call `createBond()` with that device.
3. See error

**Expected behavior**
`createBond() ` should initiate the bonding process ond Android 10

**Plugin version:**
- @capacitor-community/bluetooth-le: 3.0.0

**Smartphone (please complete the following information):**
- Device: moto g7
- OS: Android 10 
- Browser: Stock Browser

**Comment by pwespi** [comment]
No, there should be no additional step required apart from requesting device to get the ID and then calling `createBond`.

Does it work to create the bond with another app, e.g. nRF connect for mobile?
