### ISSUE TITLE
Bluetooth printer

### ISSUE THREAD

**Issue by shahketul11** [capacitor-community/bluetooth-le#550]
**Describe the bug**
I ain't able to scan a bluetooth printer using this plugin in ionic react app

Plugin version:
- @capacitor-community/bluetooth-le: [e.g. ^3.0.0]

Desktop:

Smartphone:
- Device: [e.g. Redmi note 7 pro]

**Comment by pwespi** [comment]
This plugin only support Bluetooth **Low Energy**. Most Bluetooth printers use Bluetooth Classic as far as I know. Which printer are you using?
