### ISSUE TITLE
Enable function not working on Android

### ISSUE THREAD

**Issue by ricklens** [capacitor-community/bluetooth-le#555]
**Describe the bug**
When disabling the Bluetooth adaptor, calling the enable function doesn't enable the BT adaptor, keeps raising an excepition : Enable Failed.

Also I am able to process data even if the Bluetooth adaptor is disabled.

**Comment by pwespi** [comment]
What version of Android are you using? And what device are you testing on?

The underlying `enable` and `disable` methods of `BluetoothAdapter` in Android are deprecated. See https://developer.android.com/reference/android/bluetooth/BluetoothAdapter#enable(). So the methods will be removed in a future version of the plugin and might already stop working on newer Android phones. I just added a deprecation note to the docs about this.
