### ISSUE TITLE
Android: Unable to reconnect after disabling/enabling Bluetooth

### ISSUE THREAD

**Issue by RickGroenewegen** [capacitor-community/bluetooth-le#576]
When I'm connected to a BLE device on Android and I disable Bluetooth on the Android device I am unable to reconnect to the device after enabling Bluetooth. The connect() just times out. This procedure does works on iOS with the same BLE device.

I'm not sure if this is a bug in the device itself or Android. But manually disconnecting from the device, then disabling Bluetooth, enabling again allows me to connect again, so it seems a device does not get disconnected properly when BLE is disabled and doesn't accept new connections.

Is there some event I can listen to so I can disconnect the device before Bluetooth is disabled on Android?

**Comment by pwespi** [comment]
Can you try calling `disconnect` just before `connect`?

I have never been able to reproduce this with my test devices, but we've had similar reports from people saying that connecting with peripherals that were previously connected fails on very specific Android phones.

What phone and Android version are you using? Do you have other phones to test with?

See also [Troubleshooting: Connection fails on Android](https://github.com/capacitor-community/bluetooth-le#connection-fails-on-android).
