### ISSUE TITLE
The maximal number of devices that can connect simultaneously

### ISSUE THREAD

**Issue by abdelkarimmamen** [capacitor-community/bluetooth-le#601]
I'm using the BLE plugin to connect with Polar verity sense, which works perfectly.
but I have a  problem with the number of devices that can connect simultaneously to the phone.
I want to connect more than 20 devices but when I reach to 10 devices it shows me an error.
"BtGatt.GattService      com.android.bluetooth                E  App 'app' has registered too much clientif"

so did someone face this issue and overcome it? 
if it's the case for anyone please give me some information and thanks.

**Comment by pwespi** [comment]
Hello, thank you for using this plugin.

I have never tested connecting more than 5 devices. However there is nothing in the plugin that limits the number of connected devices. Therefore I assume this limitation comes directly from Android. Maybe you'll find more information in Android forums.

Have you tested several Android devices? What Android version are you using?
