### ISSUE TITLE
iOS Cannot Reconnect on app restart

### ISSUE THREAD

**Issue by superami-code** [capacitor-community/bluetooth-le#609]
I am developing an Angular/Capacitor App and when the app hot reloads while connected, I can't reconnect to the BLE device. I've tried disconnecting from the device if connect doesn't work. The disconnect it successful, but connection still doesn't work. Power cycling the BLE device doesn't work either. The only way to reconnect is to kill and restart the app or disconnect the device in iOS Settings.

This also seems to happen in an early TestFlight build, where the user returned to the app after some time had passed and they had to kill the app before they could reconnect to the BLE device.

Is there some way to completely reset the interface?

@capacitor-community/bluetooth-le 3.1.1
@capacitor/core 5.0.3
@angular/core 17.06

**Comment by pwespi** [comment]
Have you tried using [getConnectedDevices](https://github.com/capacitor-community/bluetooth-le#getconnecteddevices)?
