### ISSUE TITLE
getDevices not working

### ISSUE THREAD

**Issue by robsonos** [capacitor-community/bluetooth-le#613]
**Describe the bug**
Devices do not connect after a disconnect on iOS. `getDevices` should do the trick but it does not seem to be working. Calling `connect` on a `BleDevice` returned form `getDevices` results in a timeout.

**To Reproduce**
```typescript
// routine used for reconnections
const devices = await BleClient.getDevices([this.device.deviceId]);
const deviceToReconnect = devices.find((device) => device.deviceId === this.device.deviceId);
await BleClient.connect(deviceToReconnect.deviceId, (deviceId) => console.warn('Disconnected from: ', deviceId));
```

**Expected behavior**
BLE should connect with data returned by `getDevices`

**Plugin version:**
- @capacitor-community/bluetooth-le: 3.1.1

**Comment by pwespi** [comment]
I cannot reproduce the problem you're describing. Can you share the logs from Xcode?
