### ISSUE TITLE
Clicking Bluetooth button on this site to request device list doesn’t bring up picker, error log

### ISSUE THREAD

**Issue by FoxMcWeezer** [capacitor-community/bluetooth-le#615]
**Describe the bug**

**To Reproduce**
1. Go to https://pof.eslack.org/gan-scrambler/
2. Click on the Bluetooth device picker button in the top right
3. No picker appears
4. Bluetooth logs show “RequestDevice Request payload could not parsed” and “GetDevices”

**Expected behavior**
Expect the device picker to appear, or at least show concise error

**Screenshots**
![IMG_5195](https://github.com/capacitor-community/bluetooth-le/assets/5359456/7528636f-f194-4089-8a11-3f2fe3043674)

**Plugin version:**
- @capacitor-community/bluetooth-le: [e.g. 0.4.0]

**Desktop (please complete the following information):**
- OS: iOS
- Browser Bluefy for iOS
- Version 3.9.0

**Smartphone (please complete the following information):**

**Additional context**
Likely an issue with Bluefy. Bluetooth picker works fine for this site on other browsers, and Android

**Comment by pwespi** [comment]
Yes, looks like a Bluefy issue to me. 

What are the filters you're passing to `requestDevice`. Have you tried different options for the call?
