### ISSUE TITLE
Android only shows "Unknown" device name when scanning with requestDevice()

### ISSUE THREAD

**Issue by mley** [capacitor-community/bluetooth-le#633]
**Describe the bug**
When using the `requestDevice()` method to scan for BLE heart-rate monitors, Android shows the devices only as "Unknown" with their MAC address. I test this with a Polar H9 and a Garmin watch in broadcast mode. On iOS the names of the devices are shown correctly.

```
await BleClient.requestDevice({
        services: ['0000180d-0000-1000-8000-00805f9b34fb'],
        scanMode: ScanMode.SCAN_MODE_LOW_LATENCY,
      });
```

**To Reproduce**
1. Turn on BLE HR monitor
2. Call requestDevice()
3. See result

**Expected behavior**
I expect the pick device dialog to also show the name of the device

**Screenshots**
![Screenshot_20240308_094002_FIT-UP](https://github.com/capacitor-community/bluetooth-le/assets/7995757/163816d2-c560-4642-b5f2-992b3b0676a7)

![Bildschirmfoto 2024-03-08 um 09 45 17](https://github.com/capacitor-community/bluetooth-le/assets/7995757/03cf0cf9-ab11-48f1-ae8a-c4f77a47a746)

**Plugin version:**
- @capacitor-community/bluetooth-le: 3.1.2

**Smartphone (please complete the following information):**
- Device: Samsung Galaxy A22
- OS: Android 13
- Browser: Chrome

**Comment by pwespi** [comment]
I'm unable to reproduce this on my test devices. Are you seeing this on multiple Android devices?

**Comment by peitschie** [comment]
Worth noting, iOS has 2 mechanisms for reporting BLE name, while Android only uses the advertised name. I wonder if the above is only showing the GAP name in iOS, which is cached after connection?

See https://forums.developer.apple.com/forums/thread/19381

@mley capturing the specific advertising packet using nrf Connect would perhaps make it clearer what's being broadcast.

**Comment by mley** [comment]
Thanks for the reply. 

I tried again today with the same Android device and the same Polar H9 and this time the name of the device came back correctly. It might have just been a hiccup, fixed by a reboot of the Android phone...

Sorry for the inconvenience. I will close the issue then.

**Comment by lroal** [comment]
I still have this isse with v 7.2.0
