### ISSUE TITLE
[iOS] App disconnect after timout time 

### ISSUE THREAD

**Issue by MasDevProject** [capacitor-community/bluetooth-le#659]
**Describe the bug**
Using the following code on iOS the connection is interrupted after 5000ms even if the device is exchanging data.
This happen only on iOS, on Android everything is ok.
It seems that the connection is interrupted after the time specified in timeout parameter.

```
BleClient.connect(deviceId, (deviceId) => this.deviceDisconnected.next(deviceId), { timeout: 5000 })
```

**To Reproduce**
Use the code above

**Expected behavior**
The timeout should interrupt the connection only if the devices is not able to exchange data.

**Plugin version:**
- @capacitor-community/bluetooth-le: 6.0.0

**Comment by laban405** [comment]
Having same problem, any solution?

**Comment by MasDevProject** [comment]
As a workaround we used a long timeout on ios platform..

```
BleClient.connect(deviceId, , { timeout: this.platform.is('ios') ? 60000 * 60 : 5000 })
```

**Comment by peitschie** [comment]
This could potentially happen if there are no services to discover on the device, or service discovery somehow fails.
Perhaps it's worth trying with another BLE program to confirm the service discovery phase is working correctly for your peripheral?

**Comment by laban405** [comment]
> This could potentially happen if there are no services to discover on the device, or service discovery somehow fails. Perhaps it's worth trying with another BLE program to confirm the service discovery phase is working correctly for your peripheral?

BLE scanner works well, also nrF Connect on the same device

**Comment by peitschie** [comment]
What services are available after connection?
