### ISSUE TITLE
Connecting device2 delays writing data to device1

### ISSUE THREAD

**Issue by stefanhaebler** [capacitor-community/bluetooth-le#678]
**Describe the bug**
My application connects to multiple bluetooth lamps in parallel `BleClient.connect(...)`. These lamps are not part of a common bluetooth network and don't know anything about each other.
Then I send flashing instructions every second to some of those lamps `BleClient.write(..)`, same service, same characteristics, same data.
All works fine until here.

If now, e.g. triggered by a new lamp bluetooth discovery, a new connection is initiated to this new lamp, the continuous sending of the flashing instructions is interrupted/delayed until this new connection is established.

Following scenario in this [flashing interruption log.txt](https://github.com/user-attachments/files/16626271/flashing.interruption.log.txt):
Connecting to the new lamp takes 3.7 seconds (`C5:B0:AA:EC:69:34`), and writing the flashing instructions takes therefore 3.2 seconds  (`F7:93:5B:0C:29:E4` and `D0:CF:5E:E1:2C:30`). Writing flashing instructions normally takes ~100ms.
The time measuring is taken like this:
```
public connectDevice(deviceId: string, onDisconnect: (deviceId: string) => void): Promise<void> {
  console.time(`removeme ${deviceId} connectDevice`);
  console.timeLog(`removeme ${deviceId} connectDevice`, 'start');
  return BleClient.connect(deviceId, onDisconnect).finally(() => {
    console.timeLog(`removeme ${deviceId} connectDevice`, 'end');
    console.timeEnd(`removeme ${deviceId} connectDevice`);
  });
}

public write(
  deviceId: string,
  serviceId: BluetoothServiceUuid,
  characteristicId: BluetoothCharacteristicUuid,
  requestData: ArrayBuffer
): Promise<void> {
  console.time(`removeme ${deviceId} write`);
  console.timeLog(`removeme ${deviceId} write`, 'start');
  return BleClient.write(deviceId, serviceId, characteristicId, new DataView(requestData)).finally(() => {
    console.timeLog(`removeme ${deviceId} write`, 'end');
    console.timeEnd(`removeme ${deviceId} write`);
  });
}
```

I wonder if `bluetooth-le` is somehow blocking itself when running multiple connections? Or can I somehow better address this problem with different connection/writing options...?

**Expected behavior**
I would expect the flashing to continue normally.

**Plugin version:**
- @capacitor-community/bluetooth-le: 6.0.1

**Smartphone (please complete the following information):**
- Device: Google Pixel 6
- OS: Android 14
- Browser: Ionic React Application
- Version: 8.2.5

**Comment by peitschie** [comment]
@stefanhaebler I've had a quick squizz, but nothing in particular stands out to me about this. As far as I can tell (perhaps @pwespi can confirm with more confidence... I'm still finding my way through the codebase a bit)... there shouldn't be anything here that would stop you writing to one device while connecting to another...

**Comment by pwespi** [comment]
There is actually a queue for method calls in the JavaScript layer of the plugin. I suspect what you're seeing is caused by it. It was introduced to avoid concurrency issues in the BLE stack, but it might be too restricting for your use case.

There is an undocumented way to disable it with `BleClient.disableQueue()` that you could use. But be aware that this might have other side effects.
