### ISSUE TITLE
Add Bluetooth Disconnect Reasons

### ISSUE THREAD

**Issue by dennisheerwb** [capacitor-community/bluetooth-le#686]
**Is your feature request related to a problem? Please describe.**
For better error investigation on client devices that we do not have access to, it would be helpful to determine the reason why Bluetooth has been disconnected.

**Describe the solution you'd like**
I hereby propose an enhancement to the `onDisconnect`-callback of the [connect method](https://github.com/capacitor-community/bluetooth-le?tab=readme-ov-file#connect) to provide the disconnect reason, ideally in alignment with the `HCI_DISCONNECT` specification.

- [Host Controller Interface Functional Specification](https://www.bluetooth.com/wp-content/uploads/Files/Specification/HTML/Core-54/out/en/host-controller-interface/host-controller-interface-functional-specification.html#UUID-332adb1f-b5ac-5289-82a2-c51a59d533e7)
- [Controller Error Codes](https://www.bluetooth.com/wp-content/uploads/Files/Specification/HTML/Core-54/out/en/architecture,-mixing,-and-conventions/controller-error-codes.html)

**Comment by peitschie** [comment]
Unfortunately, we generally don't get any of this information passed back from OS itself.

Android simply returns the state as disconnected ([source](https://github.com/capacitor-community/bluetooth-le/blob/ee6d9671090eb1bca6841086e8da95cde074fd54/android/src/main/java/com/capacitorjs/community/plugins/bluetoothle/Device.kt#L107)).

iOS gives an error which is converted into a string and reported back to the caller ([source](https://github.com/capacitor-community/bluetooth-le/blob/ee6d9671090eb1bca6841086e8da95cde074fd54/ios/Plugin/DeviceManager.swift#L277)).

* Android: https://developer.android.com/reference/android/bluetooth/BluetoothGattCallback#onConnectionStateChange(android.bluetooth.BluetoothGatt,%20int,%20int)
* iOS: https://developer.apple.com/documentation/corebluetooth/cbcentralmanagerdelegate/centralmanager(_:diddisconnectperipheral:error:)


While I agree the information would be useful, I don't know what can be done here to improve the situation.
