### ISSUE TITLE
Enable ScanMode option in requestLEScan for IOS

### ISSUE THREAD

**Issue by madhan-SEET** [capacitor-community/bluetooth-le#692]
Enable the 'Scan Mode' option in the requestLEScan(...) method. In iOS balance mode, it currently does not capture packets effectively compared to low latency mode.

**Comment by pwespi** [comment]
Hello. The `ScanMode` that is currently implemented in this plugin is for Android only. iOS does not support this as far as I know, see https://developer.apple.com/documentation/corebluetooth/peripheral-scanning-options

I'm closing this feature request as I don't think it's possible to implement. If you know any option available in iOS let me know and I'll reopen.
