### ISSUE TITLE
BleClient.writeWithoutResponse undefined 

### ISSUE THREAD

**Issue by tpRamakrishna** [capacitor-community/bluetooth-le#713]
**Describe the bug**

**To Reproduce**

able to connect to the device 
BleClient.writeWithoutResponse is giving a response as undefined.

**Comment by peitschie** [comment]
Hi @tpRamakrishna 

What response are you expecting? Are you able to post a code snippet demonstrating the problem?

**Comment by tpRamakrishna** [comment]
const battery = await BleClient.read(this.deviceId, this.serviceId, this.characteristicUuid);
    console.log('battery level', battery.getUint8(0));
    const boldOn = new Uint8Array([27, 69, 1]);
     await BleClient.writeWithoutResponse(this.deviceId, this.serviceId, this.characteristicUuid, new DataView(boldOn.buffer));
  
let array = new Uint8Array([0xCC, 0x24, 0x33]);
    await BleClient.writeWithoutResponse(this.deviceId, this.serviceId.toLowerCase(), this.characteristicUuid.toLowerCase(), new DataView(array.buffer));


I can connect to the device and get the notifications from the device and also getting response onse also but visually print is not happening from the printer.

**Comment by peitschie** [comment]
Unfortunately, this is going to be related to the commands you need to send to the Bluetooth printer itself. This isn't an area I can really help with, as it's not really about Bluetooth itself.

You'll need to look at the printer's SDK or interface documentation to figure out the right structures to send.

Having said that, if you do find a case where the plugin does not send the right information, do feel free to re-open this ticket.
