### ISSUE TITLE
multiple Notifications not working

### ISSUE THREAD

**Issue by pentabarf** [capacitor-community/bluetooth-le#74]
It is not possible to do multiple Notifications on the same device but different characteristics.
It throws an error that the second notification can not be subscribed.

I stumbled over this some days ago using Android. I will post the exact error message when coming to this again. but it is easy to reproduce. Just start two notifications.

**Comment by pwespi** [comment]
Probably related to #64 which has been implemented in v0.5.0 (for Capacitor v2) and v1.0.0-2 (for Capacitor v3).

So this should be fixed. (Let me know if it isn't).
