### ISSUE TITLE
startNotifications doesn't clean up after reconnect

### ISSUE THREAD

**Issue by pentabarf** [capacitor-community/bluetooth-le#75]
related to #65: the same happens when reconnecting to the same device after connection broke up. I have a routine which automatically searches for the device in case the connection gets lost and restarts all running notifications.
after the reconnect and restart of notifications, every notification fires twice or more (one more per reconnect)
I restarted my BLE device to simulate a connection loss (e.g. distance between ble-device and smart-device is to large)
There has to be a cleanup of native notification listeners in case of broken connection.

**Comment by pwespi** [comment]
Thanks for this issue. It has been fixed in v0.5.0 (for Capacitor v2) and v1.0.0-2 (for Capacitor v3). I assume this was in Android?
