### ISSUE TITLE
When connect fails due to timeout and BLE device becomes available, the stack connects to device, even though the Promise was already rejected

### ISSUE THREAD

**Issue by smartifier-salomaa** [capacitor-community/bluetooth-le#80]
**Describe the bug**
If connect fails and promise is rejected, the stack should clear the connect request. Now, the connection may happen later but there is no way to notify the app as there is no 'onConnected' callback option.

**To Reproduce**
1. Discover devices using requestLEScan
2. Make sure your BLE device is discovered.
3. Switch off the BLE device or move out of reach
4. Try to establish connection to BLE device.
5. Wait until Promise is Rejected due to timeout.
6. Switch on the BLE device (or bring to connection reach).
7. Stack connects to device automatically (Connected to device <CBPeripheral: 0x281d599a0, identifier = 1234, name = Something, state = connected>)

**Expected behavior**
If Connect promise is already rejected, nothing should happen even if the device could be connected later. Or alternatively, if there would be onConnected callback, this could be called but it might confuse the app logic.

**Plugin version:**
- @capacitor-community/bluetooth-le: 1.0.0-1

**Smartphone (please complete the following information):**
- Device: iPhone 8 Plus
- OS: 14.4.1

**Comment by pwespi** [comment]
Thanks for this issue and the detailed description. 

It has been fixed in v0.5.0 (for Capacitor v2) and v1.0.0-2 (for Capacitor v3) for Android and iOS. Unfortunately on web in Chromium this is blocked by https://bugs.chromium.org/p/chromium/issues/detail?id=684073.
