### ISSUE TITLE
Module not found: Error: Can't resolve 'throat'

### ISSUE THREAD

**Issue by smartifier-salomaa** [capacitor-community/bluetooth-le#81]
**Describe the bug**
After upgrading from 1.0.0-1 to 1.0.0-2 I'm getting this error when compiling:
`Module not found: Error: Can't resolve 'throat'`

**To Reproduce**
1. Upgrade plugin to version 1.0.0-2 `'npm install @capacitor-community/bluetooth-le@1.0.0-2'`
2. `npx cap sync`
3. Try to compile with `ionic build`
```
Error: ./node_modules/@capacitor-community/bluetooth-le/dist/esm/queue.js
Module not found: Error: Can't resolve 'throat'
```

**Expected behavior**
Dependencies should be automatically updated and build should run through

**Plugin version:**
- @capacitor-community/bluetooth-le: 1.0.0-2

**Comment by pwespi** [comment]
Thanks for reporting this. It has been fixed in 1.0.0-3.
