### ISSUE TITLE
In the introduction the implementation status link refers to non existing page

### ISSUE THREAD

**Issue by hjvanranden** [capacitor-community/bluetooth-le#94]
**To Reproduce**
1. Go to https://github.com/capacitor-community/bluetooth-le#introduction
2. Click on link 'see implementation status' (referring to https://github.com/WebBluetoothCG/web-bluetooth/blob/gh-pages/implementation-status.md).

**Observed behavior**
404 error
![404](https://user-images.githubusercontent.com/11467054/114081353-bac1ec00-98ac-11eb-8a43-984b03565b1c.PNG)

**Expected behavior**
You see page describing the implementation status

**Comment by pwespi** [comment]
The link has been fixed. Thanks for reporting this. 👍
